#!/usr/bin/env bash
# Build the commit message and PR/comment body that describe WHAT the auditor changed, from the
# auditor's own final summary plus the guardrail's list of edited docs. Run only after the
# guardrail reports changed=true, while the doc edits are still uncommitted in the working tree.
#
# Emits, into $RUNNER_TEMP:
#   docs-sentinel-commit.txt — git commit message (subject + body), for `git commit -F`
#   docs-sentinel-body.md    — markdown PR description / PR comment body
# and three GitHub step outputs: commit_path, body_path, and commit_message (multiline).
set -euo pipefail

: "${FILES_PATH:?FILES_PATH not set}"          # guardrail's list of edited doc paths (one per line)
SUMMARY_PATH="${SUMMARY_PATH:-}"               # auditor's final summary (may be missing/empty)
SHA="${SHA:-}"
: "${GITHUB_OUTPUT:?GITHUB_OUTPUT not set}"

TMP="${RUNNER_TEMP:-/tmp}"
BODY="$TMP/docs-sentinel-body.md"
COMMIT="$TMP/docs-sentinel-commit.txt"

# The auditor's own description of what it changed and why — drop it in verbatim if present.
SUMMARY=""
if [ -n "$SUMMARY_PATH" ] && [ -s "$SUMMARY_PATH" ]; then
  SUMMARY=$(cat "$SUMMARY_PATH")
fi

# Split an optional leading "Subject: <one line>" off the auditor's summary. The auditor emits it
# only in its "edited docs" output shape; the remainder is the commit/PR body prose. Everything
# structural (the type-shape fallback, the skip marker) stays shell-owned below.
DEFAULT_SUBJECT="docs: sync documentation with code changes"
SUBJECT=""
BODY_SUMMARY="$SUMMARY"
if [ -n "$SUMMARY" ]; then
  first="${SUMMARY%%$'\n'*}"                       # first line (whole string if no newline)
  case "$first" in
    "Subject: "*)
      SUBJECT="${first#Subject: }"
      # Drop line 1 and, if present, a single blank separator line after it.
      BODY_SUMMARY="$(printf '%s\n' "$SUMMARY" | awk 'NR==1{next} NR==2 && $0==""{next} {print}')"
      ;;
  esac
fi

# Validate the subject: single line, non-empty, within the conventional header cap (100). The skip
# marker is no longer part of the subject, so the whole budget is the auditor's. Fall back to the
# static subject on anything unusable, so a malformed line can never become the commit header.
SUBJECT="$(printf '%s' "$SUBJECT" | tr -d '\r\n')"
if [ -z "$SUBJECT" ] || [ "${#SUBJECT}" -gt 100 ]; then
  SUBJECT="$DEFAULT_SUBJECT"
fi

short="${SHA:0:12}"

# The auditor's edits are still uncommitted, so `git diff` over the edited docs gives the ACTUAL
# content change. Cap it so a PR comment stays readable; note when truncated.
DIFF_CAP=16000
DOC_DIFF="$TMP/docs-sentinel-docdiff.diff"
_files=()
while IFS= read -r _f; do
  if [ -n "$_f" ]; then _files+=("$_f"); fi
done < "$FILES_PATH"
FULL_DIFF="$TMP/docs-sentinel-docdiff.full"
# An empty pathspec list would mean `git diff -- ` (the WHOLE tree) — guard it.
if [ "${#_files[@]}" -eq 0 ]; then
  : > "$FULL_DIFF"
else
  git diff --no-color -- "${_files[@]}" > "$FULL_DIFF" 2>/dev/null || : > "$FULL_DIFF"
fi
head -c "$DIFF_CAP" "$FULL_DIFF" > "$DOC_DIFF"
DIFF_NOTE=""
if [ "$(wc -c < "$FULL_DIFF")" -gt "$DIFF_CAP" ]; then
  DIFF_NOTE=" (truncated — see the PR's *Files changed* tab for the rest)"
fi

# ── PR description / PR comment body (markdown) ──────────────────────────────
{
  printf '🤖 **Docs audit** updated documentation to match the code change'
  # shellcheck disable=SC2016
  if [ -n "$SHA" ]; then printf ' in `%s`' "$short"; fi
  printf '.\n\n'
  if [ -n "$BODY_SUMMARY" ]; then
    echo "**What changed and why**"
    echo
    echo "$BODY_SUMMARY"
    echo
  fi
  echo "**Files updated**"
  echo
  # shellcheck disable=SC2016
  sed 's/^/- `/; s/$/`/' "$FILES_PATH"
  echo
  if [ -s "$DOC_DIFF" ]; then
    echo "**What changed in the docs${DIFF_NOTE}**"
    echo
    echo "<details><summary>Show doc diff</summary>"
    echo
    echo '```diff'
    cat "$DOC_DIFF"
    echo '```'
    echo
    echo "</details>"
    echo
  fi
  echo "<sub>Generated by [docs-sentinel](https://github.com/slingshot/docs-sentinel). Review these doc edits before merging.</sub>"
} > "$BODY"

# ── git commit message (subject + body) ─────────────────────────────────────
# Subject comes from the auditor (validated above, static fallback). The [skip docs-sentinel] marker
# is a FOOTER trailer, not part of the subject, so it never trips a header-length or subject rule —
# the gate greps the whole message, so a footer marker still keeps it from auditing our sync commit.
{
  echo "$SUBJECT"
  echo
  if [ -n "$BODY_SUMMARY" ]; then
    echo "$BODY_SUMMARY"
    echo
  fi
  echo "Files updated:"
  sed 's/^/  - /' "$FILES_PATH"
  echo
  echo "[skip docs-sentinel]"
} > "$COMMIT"

# Random heredoc delimiter: the commit message embeds LLM-generated summary text, and a
# predictable delimiter line inside it would terminate the block early (output injection).
DELIM="__DOCS_SENTINEL_MSG_$(od -An -N16 -tx1 /dev/urandom | tr -d ' \n')__"
{
  echo "commit_path=$COMMIT"
  echo "body_path=$BODY"
  echo "pr_title=$SUBJECT"
  echo "commit_message<<$DELIM"
  cat "$COMMIT"
  echo "$DELIM"
} >> "$GITHUB_OUTPUT"

echo "Composed docs-sentinel commit message and PR body:"
echo "----- body -----"; cat "$BODY"; echo "----------------"
