#!/usr/bin/env bash
# Decide, and render, the single sticky status comment. Extracted from inline github-script so the
# one rule that matters can be tested: an inconclusive audit must never render as a clean pass.
#
# There is deliberately no `skipped` outcome: the skip comment is posted by the comment-pr-skip
# job, which cannot reach this script (see the plan's note on reusable-workflow checkout).
#
# Env contract:
#   OUTCOME      (required)  fixed | clean | inconclusive | infra
#   KIND         (optional)  for inconclusive: hygiene | execution | guardrail | push
#   EDITS_LANDED (optional)  "true" when doc fixes were committed despite an inconclusive result
#   REASON       (optional)  one-line explanation
#   BODY         (optional)  pre-composed markdown body, used by `fixed`
#   RUN_URL      (optional)  link to the workflow run
set -euo pipefail

: "${OUTCOME:?OUTCOME not set}"
KIND="${KIND:-}"
EDITS_LANDED="${EDITS_LANDED:-false}"
REASON="${REASON:-}"
BODY="${BODY:-}"
RUN_URL="${RUN_URL:-}"

FOOTER='<sub>Generated by [docs-sentinel](https://github.com/slingshot/docs-sentinel).</sub>'

# `[ -n "$X" ] && printf ...` is the last command in several branches; under `set -e` a false test
# would abort. Each is written as a full `if` for that reason.
case "$OUTCOME" in
  fixed)
    printf '%s\n' "$BODY"
    ;;
  clean)
    echo '🤖 **Docs audit** — no documentation drift detected.'
    echo
    if [ -n "$REASON" ]; then printf '%s\n\n' "$REASON"; fi
    printf '%s\n' "$FOOTER"
    ;;
  inconclusive)
    echo '⚠️ **Docs audit — inconclusive.** This change has **not** been confirmed free of documentation drift.'
    echo
    case "$KIND" in
      hygiene)
        echo 'The auditor completed, but its summary was unusable, so its result could not be verified.'
        ;;
      execution)
        echo 'The audit did not complete — the run crashed, timed out, or the model provider errored. Any edits it had made were discarded.'
        ;;
      guardrail)
        echo 'The auditor edited files outside the documentation allowlist or exceeded the churn budget, so **every** edit was reverted.'
        ;;
      push)
        echo 'Documentation fixes were produced, but they could not be committed to this branch.'
        ;;
      *)
        echo 'The auditor did not produce a usable result.'
        ;;
    esac
    echo
    if [ "$EDITS_LANDED" = "true" ]; then
      echo '**Documentation fixes were still committed to this PR** — they passed the guardrail — but they are undescribed. Review them directly in the diff.'
      echo
    fi
    # shellcheck disable=SC2016  # backticks are literal markdown code fencing, not substitution
    if [ -n "$REASON" ]; then printf 'Reason: `%s`\n\n' "$REASON"; fi
    if [ -n "$RUN_URL" ]; then printf '[View the run](%s)\n\n' "$RUN_URL"; fi
    printf '%s\n' "$FOOTER"
    ;;
  infra)
    echo '⚠️ **Docs audit — could not run.** Setup failed before the audit started, so this change has **not** been checked for documentation drift.'
    echo
    if [ -n "$RUN_URL" ]; then printf '[View the run](%s)\n\n' "$RUN_URL"; fi
    printf '%s\n' "$FOOTER"
    ;;
  *)
    echo "::error::Unknown OUTCOME '$OUTCOME'" >&2
    exit 1
    ;;
esac
